import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {GraphQLClient,gql} from 'graphql-request';
const graphcms= new GraphQLClient(
  "https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/cla0pikzo46d801tb7claff3z/master"
);
import BlogCard from "../components/BlogCard"
import { Key } from 'react';
const QUERY =gql`
{
  postsMUN{
    title,
    slug,
    category,
  coverPhoto{
    url
  },
    content{
      html
    },
    author{
      name,
      avatar{
        url
      }
    },
  }
 }
`
export async function getStaticProps() {
  const {postsMUN}=await graphcms.request(QUERY);
  return {
    props:{
      postsMUN,
    },
    revalidate : 10,
  };
}
  
export default function Home({ postsMUN }:any ) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>

    </header>
      <h1> BacauMUN Blog</h1>
      <main className={styles.main}>

        {postsMUN.map((postMUN: { title: any; category: any; author: any; coverPhoto: any; id: Key | null | undefined; slug: any; }) => (
          <BlogCard title={postMUN.title} 
          category={postMUN.category}
          author={postMUN.author} 
          coverPhoto={postMUN.coverPhoto}
           key={postMUN.id} 
           slug={postMUN.slug}/>
        ))}
      </main>

      <div className={styles.bottom}>

          <a href="https://bacaumun.com/" target="_blank"
            ><h2>Back to the main website</h2></a>

      </div>
    </div>
  )
}
