import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {GraphQLClient,gql} from 'graphql-request';
const graphcms= new GraphQLClient(
  "https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/cla0pikzo46d801tb7claff3z/master"
);
import BlogCard from "../components/BlogCard"
const QUERY =gql`
{
  postsMUN{
    title,
    slug,
    category,
  coverPhoto{
    url
  },
    content{
      html
    },
    author{
      name,
      avatar{
        url
      }
    },
  }
 }
`
export async function getStaticProps() {
  const {postsMUN}=await graphcms.request(QUERY);
  return {
    props:{
      postsMUN,
    },
    revalidate : 10,
  };
}
  
export default function Home({postsMUN}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>

        {postsMUN.map((postmun)=>(
          <BlogCard title={postmun.title} 
          category={postmun.category}
          author={postmun.author} 
          coverPhoto={postmun.coverPhoto}
           key={postmun.id} 
           slug={postmun.slug}/>
        ))}
      </main>

    </div>
  )
}
